class Constantes:
    tipoCruzamento = "TIPO_CRUZAMENTO"
    temElitismo = "TEM_ELITISMO"
    tipoSelecao = "TIPO_SELECAO"
    tipoMutacao = "TIPO_MUTACAO"
    taxaCruzamento = "TAXA_CRUZAMENTO"
    taxaMutacao = "TAXA_MUTACAO"
    numeroIndividuos = "N_INDIVIDUOS"
    numeroGeracao = "N_GERACAO"
    ensaio= "N_ENSAIO"
    numeroExecucao = "N_EXECUCAO"